import { useState } from 'react'
import {
	AlertTriangle, ArrowLeft, Bell, Check, ChevronRight, CircleHelp, CloudRain,
	Flame, Home, Info, Leaf, LocateFixed, LogOut, Map, Menu, MessageCircle,
	Mountain, Navigation, Phone, Plus, Radio, Route, Search, Shield, Siren,
	UserRound, Users, X, Zap,
} from 'lucide-react'
import './App.css'

const incidents = [
	{ id: 'NG-2408', type: 'Road hazard', title: 'Fallen tree blocking Ooty–Coonoor road', location: 'Near Ketti Valley viewpoint', time: '12 min ago', status: 'Active', severity: 'High', icon: Route, color: 'coral' },
	{ id: 'NG-2407', type: 'Wildlife alert', title: 'Elephant movement reported near Aravenu', location: 'Kotagiri block', time: '34 min ago', status: 'Monitoring', severity: 'Medium', icon: Leaf, color: 'lime' },
	{ id: 'NG-2406', type: 'Weather', title: 'Heavy rainfall and low visibility', location: 'Coonoor, Wellington', time: '1 hr ago', status: 'Active', severity: 'Medium', icon: CloudRain, color: 'blue' },
]

const navItems = [
	{ label: 'Dashboard', icon: Home, view: 'dashboard' },
	{ label: 'Live safety map', icon: Map, view: 'map' },
	{ label: 'Emergency alerts', icon: Bell, view: 'alerts', count: 2 },
	{ label: 'My reports', icon: Radio, view: 'reports' },
]

function IconButton({ children, label, onClick, className = '' }) {
	return <button className={`icon-button ${className}`} aria-label={label} title={label} onClick={onClick}>{children}</button>
}

function StatusPill({ children, tone = 'green' }) { return <span className={`status-pill ${tone}`}>{children}</span> }

function IncidentCard({ incident, onClick }) {
	const Icon = incident.icon
	return <button className="incident-card" onClick={onClick}>
		<div className={`incident-icon ${incident.color}`}><Icon size={19} /></div>
		<div className="incident-copy"><div className="eyebrow-row"><span>{incident.type}</span><span>{incident.time}</span></div><strong>{incident.title}</strong><small><Navigation size={12} /> {incident.location}</small></div>
		<div className="incident-right"><StatusPill tone={incident.severity === 'High' ? 'red' : 'amber'}>{incident.status}</StatusPill><ChevronRight size={17} /></div>
	</button>
}

function MapPreview({ expanded = false, onExpand }) {
	return <div className={`map-preview ${expanded ? 'expanded' : ''}`}>
		<div className="map-toolbar"><div className="map-label"><span className="live-dot" /> LIVE COMMUNITY MAP</div><IconButton label="Center map"><LocateFixed size={17} /></IconButton></div>
		<div className="map-grid" />
		<div className="mountain-lines" />
		<div className="map-road road-one" /><div className="map-road road-two" /><div className="map-road road-three" />
		<div className="map-place ooty">Ooty <span>•</span></div><div className="map-place coonoor">Coonoor</div><div className="map-place kotagiri">Kotagiri</div>
		<span className="map-pin pin-red" /><span className="map-pin pin-orange" /><span className="map-pin pin-lime" /><span className="map-pin pin-blue" />
		{!expanded && <button className="map-expand" onClick={onExpand}><Map size={15} /> Open live map <ChevronRight size={15} /></button>}
		{expanded && <div className="map-legend"><span><i className="legend-dot red" /> Critical</span><span><i className="legend-dot orange" /> Road hazard</span><span><i className="legend-dot lime" /> Wildlife</span></div>}
	</div>
}

function Sidebar({ view, setView, onReport, menuOpen }) {
	return <aside className={`sidebar ${menuOpen ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><Shield size={20} /></div><div><b>nilgiri<span>guardian</span></b><small>Community safety network</small></div></div><div className="side-section"><span className="side-label">Workspace</span>{navItems.map(({ label, icon: Icon, view: itemView, count }) => <button key={itemView} className={`nav-item ${view === itemView ? 'active' : ''}`} onClick={() => setView(itemView)}><Icon size={18} /><span>{label}</span>{count && <em>{count}</em>}</button>)}</div><button className="report-button" onClick={onReport}><Plus size={19} /> Report incident</button><div className="sidebar-bottom"><div className="connection"><span className="live-dot" /><div><b>Network connected</b><small>Last synced just now</small></div></div><button className="profile-link" onClick={() => setView('profile')}><div className="avatar small">AS</div><span><b>Ananya Sharma</b><small>Resident · Ooty</small></span><ChevronRight size={15} /></button></div></aside>
}

function Header({ view, setView, onMenu }) {
	const labels = { dashboard: 'Good morning, Ananya', map: 'Live safety map', alerts: 'Emergency alerts', reports: 'My reports', details: 'Incident details', contacts: 'Emergency contacts', profile: 'Your profile' }
	return <header className="topbar"><div className="mobile-brand"><div className="brand-mark"><Shield size={18} /></div><b>nilgiri<span>guardian</span></b></div><div className="page-heading"><button className="back-button" onClick={() => setView('dashboard')}><ArrowLeft size={16} /></button><div><span className="crumb">NILGIRI GUARDIAN / {view === 'dashboard' ? 'OVERVIEW' : view.toUpperCase()}</span><h1>{labels[view]}</h1></div></div><div className="header-actions"><div className="search-box"><Search size={16} /><input placeholder="Search reports, places..." /></div><IconButton label="Help and support"><CircleHelp size={19} /></IconButton><button className="notification-button" aria-label="Notifications" onClick={() => setView('alerts')}><Bell size={19} /><span>2</span></button><div className="avatar">AS</div><IconButton label="Open menu" className="mobile-menu" onClick={onMenu}><Menu size={21} /></IconButton></div></header>
}

function Dashboard({ setView }) {
	return <><div className="welcome-row"><div><p className="date-line">THURSDAY, 24 AUGUST 2026 <span className="green-dot" /> ALL SYSTEMS NORMAL</p><h2>Keeping the hills<br /><i>safer, together.</i></h2><p className="welcome-copy">Stay informed, report what you see, and look out for your community across the Nilgiris.</p></div><div className="weather-card"><CloudRain size={22} /><div><b>18°C</b><span>Ooty · Light rain</span></div><span className="weather-time">Updated 8:42 AM</span></div></div><div className="quick-actions"><button onClick={() => setView('report')}><span className="action-icon coral"><Siren size={20} /></span><span><b>Report an incident</b><small>Alert your community</small></span><ChevronRight size={18} /></button><button onClick={() => setView('map')}><span className="action-icon dark"><Map size={20} /></span><span><b>Explore live map</b><small>See what's happening nearby</small></span><ChevronRight size={18} /></button><button onClick={() => setView('contacts')}><span className="action-icon lime"><Phone size={20} /></span><span><b>Get help now</b><small>Emergency contacts</small></span><ChevronRight size={18} /></button></div><div className="section-heading"><div><span className="section-kicker">AROUND YOU</span><h3>Recent community reports <span>·</span></h3></div><button className="text-button" onClick={() => setView('reports')}>View all <ChevronRight size={15} /></button></div><div className="incident-list">{incidents.map(item => <IncidentCard key={item.id} incident={item} onClick={() => setView('details')} />)}</div><div className="dashboard-lower"><div><div className="section-heading compact"><div><span className="section-kicker">LIVE VIEW</span><h3>Safety map</h3></div><button className="text-button" onClick={() => setView('map')}>Expand map <ChevronRight size={15} /></button></div><MapPreview onExpand={() => setView('map')} /></div><div className="community-panel"><span className="section-kicker">COMMUNITY PULSE</span><h3>Small actions<br /><i>make a difference.</i></h3><p>12 residents helped verify reports in the last 24 hours.</p><div className="member-stack"><div className="avatar mini">RS</div><div className="avatar mini">MK</div><div className="avatar mini">+8</div><span>Active responders</span></div><button className="outline-button" onClick={() => setView('reports')}>See community activity <ChevronRight size={15} /></button></div></div></>
}

function ReportView({ setView }) { const [sent, setSent] = useState(false); return <div className="form-layout"><div className="form-intro"><span className="section-kicker">NEW REPORT</span><h2>What did you<br /><i>notice?</i></h2><p>Your report helps neighbours and local response teams act faster. You can submit anonymously.</p><div className="privacy-note"><Shield size={17} /><span><b>Your privacy matters</b><small>Location is approximate and your personal details are never shared publicly.</small></span></div></div><form className="report-form" onSubmit={e => { e.preventDefault(); setSent(true) }}>{sent ? <div className="success-state"><div className="success-icon"><Check size={28} /></div><h3>Report received</h3><p>Thank you for looking out for the Nilgiris. Your report <b>NG-2409</b> is now visible to the community.</p><button type="button" className="primary-button" onClick={() => setView('dashboard')}>Back to dashboard</button></div> : <><label>Incident type<select required defaultValue=""><option value="" disabled>Select a category</option><option>Landslide</option><option>Forest fire</option><option>Wildlife conflict</option><option>Road hazard</option><option>Other emergency</option></select></label><label>What is happening?<textarea required placeholder="Describe what you can see..."></textarea></label><label>Where is it? <span className="label-hint">Optional</span><div className="location-input"><Navigation size={16} /><input placeholder="Add a landmark or nearby place" /></div></label><div className="form-row"><label>Your name <span className="label-hint">Optional</span><input placeholder="Anonymous" /></label><label>Urgency<select defaultValue="Medium"><option>Low</option><option>Medium</option><option>High - immediate danger</option></select></label></div><label className="check-label"><input type="checkbox" defaultChecked /><span>Share this report with nearby residents</span></label><button className="primary-button" type="submit"><Siren size={17} /> Submit report</button></>}</form></div> }

function MapView({ setView }) { return <div className="full-map-view"><div className="map-side-panel"><span className="section-kicker">LIVE REPORTS · 4</span><h2>What’s happening<br /><i>right now.</i></h2><div className="filter-row"><button className="filter active">All <span>4</span></button><button className="filter">Hazards</button><button className="filter">Wildlife</button></div>{incidents.map(item => <IncidentCard key={item.id} incident={item} onClick={() => setView('details')} />)}</div><MapPreview expanded /></div> }

function AlertsView({ setView }) { return <div className="alerts-layout"><div className="alert-banner"><div className="alert-symbol"><AlertTriangle size={22} /></div><div><span>PRIORITY ALERT · 08:30 AM</span><h2>Heavy rain advisory</h2><p>IMD has issued a yellow alert for the Nilgiris. Expect reduced visibility and slippery roads through the afternoon.</p><button onClick={() => setView('details')}>Read full advisory <ChevronRight size={15} /></button></div></div><div className="section-heading"><div><span className="section-kicker">YOUR NOTIFICATIONS</span><h3>Stay in the know</h3></div><button className="text-button">Mark all as read</button></div><div className="notification-list"><div className="notice unread"><div className="notice-icon amber"><CloudRain size={18} /></div><div><b>Rainfall alert in Coonoor</b><p>Roads may be slippery near Lamb’s Rock. Take care while travelling.</p><small>Today, 8:30 AM</small></div><span className="unread-dot" /></div><div className="notice"><div className="notice-icon lime"><Leaf size={18} /></div><div><b>Wildlife movement verified</b><p>Elephant movement near Aravenu has been confirmed by Forest Department.</p><small>Today, 7:55 AM</small></div></div><div className="notice"><div className="notice-icon blue"><Info size={18} /></div><div><b>Report resolved</b><p>The fallen branch on Garden Road has been cleared. Thank you, Ravi.</p><small>Yesterday, 6:20 PM</small></div></div></div></div> }

function DetailsView({ setView }) { return <div className="details-layout"><div className="detail-main"><button className="back-link" onClick={() => setView('dashboard')}><ArrowLeft size={15} /> Back to reports</button><div className="detail-title"><div className="incident-icon coral"><Route size={25} /></div><div><span className="section-kicker">ROAD HAZARD · NG-2408</span><h2>Fallen tree blocking<br />Ooty–Coonoor road</h2><StatusPill tone="red">Active</StatusPill></div></div><div className="detail-meta"><span><Navigation size={16} /> Near Ketti Valley viewpoint</span><span><Radio size={16} /> Reported 12 min ago</span><span><Users size={16} /> 8 people notified</span></div><div className="detail-card"><span className="section-kicker">REPORT DESCRIPTION</span><p>Large eucalyptus tree has come down across the left lane after the rain. Traffic is moving slowly through one side. Please avoid the route if possible.</p><div className="verified"><Check size={15} /> Verified by 3 community members</div></div><MapPreview /></div><aside className="action-card"><h3>Can you help?</h3><p>Only respond if you are nearby and it is safe to do so.</p><button className="primary-button"><Check size={16} /> I can confirm this</button><button className="outline-button"><MessageCircle size={16} /> Add an update</button><div className="responders"><b>Community response</b><div className="progress"><span /></div><small>3 of 5 confirmations needed</small></div></aside></div> }

function ContactsView() { const contacts = [['112', 'National emergency', 'Police, ambulance & fire', 'dark'], ['1077', 'District disaster control', 'Nilgiris district helpline', 'coral'], ['0423 244 2345', 'Forest department', 'Wildlife conflict response', 'lime'], ['0423 244 3977', 'Ooty police station', 'Local police assistance', 'blue']]; return <div className="contacts-layout"><div><span className="section-kicker">HELP WHEN YOU NEED IT</span><h2>Emergency<br /><i>contacts.</i></h2><p className="intro-copy">Save these numbers. Calls connect directly to local response teams.</p></div><div className="contact-list">{contacts.map(([number, name, desc, color]) => <a className="contact-card" href={`tel:${number.replaceAll(' ', '')}`} key={number}><div className={`contact-icon ${color}`}><Phone size={20} /></div><div><b>{name}</b><span>{desc}</span></div><strong>{number}</strong><ChevronRight size={17} /></a>)}</div><div className="safety-note"><Zap size={18} /><div><b>When every second counts</b><p>Move to a safe location first, then call. Keep your location and nearest landmark ready.</p></div></div></div> }

function ProfileView({ setView }) { return <div className="profile-layout"><div className="profile-hero"><div className="avatar large">AS</div><span className="section-kicker">COMMUNITY MEMBER SINCE 2024</span><h2>Ananya Sharma</h2><p><Navigation size={14} /> Ooty, Tamil Nadu</p><StatusPill>Trusted contributor</StatusPill></div><div className="profile-stats"><div><strong>18</strong><span>Reports made</span></div><div><strong>14</strong><span>Verified reports</span></div><div><strong>246</strong><span>Community points</span></div></div><div className="profile-section"><div className="section-heading compact"><div><span className="section-kicker">YOUR ACTIVITY</span><h3>Recent reports</h3></div><button className="text-button" onClick={() => setView('reports')}>View all <ChevronRight size={15} /></button></div>{incidents.slice(0, 2).map(item => <IncidentCard key={item.id} incident={item} onClick={() => setView('details')} />)}</div><button className="logout-button"><LogOut size={16} /> Sign out</button></div> }

function ReportsView({ setView }) { return <div className="reports-layout"><div className="reports-summary"><div><span className="section-kicker">YOUR CONTRIBUTION</span><h2>Reports that<br /><i>move things.</i></h2></div><div className="big-stat"><strong>18</strong><span>total reports</span></div></div><div className="filter-row report-filters"><button className="filter active">All reports</button><button className="filter">Active</button><button className="filter">Resolved</button></div>{incidents.map(item => <IncidentCard key={item.id} incident={item} onClick={() => setView('details')} />)}</div> }

function App() { const [view, setView] = useState('dashboard'); const [menuOpen, setMenuOpen] = useState(false); const isForm = view === 'report'; return <div className="app-shell"><Sidebar view={view} setView={setView} onReport={() => setView('report')} menuOpen={menuOpen} /><div className="main-area"><Header view={view} setView={setView} onMenu={() => setMenuOpen(v => !v)} /><main className={isForm ? 'content form-content' : 'content'}>{view === 'dashboard' && <Dashboard setView={setView} />}{view === 'report' && <ReportView setView={setView} />}{view === 'map' && <MapView setView={setView} />}{view === 'alerts' && <AlertsView setView={setView} />}{view === 'details' && <DetailsView setView={setView} />}{view === 'contacts' && <ContactsView />}{view === 'profile' && <ProfileView setView={setView} />}{view === 'reports' && <ReportsView setView={setView} />}</main></div></div> }

export default App
